import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import rama from "../public/ramak.png";
import Image from "next/image";
import { FaGithub } from "react-icons/fa";
import { IoDocumentTextOutline } from "react-icons/io5"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Rama Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-0">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white px-10 ">
            <h1 className="font-burtons text-xl">RAMADEVELOPED</h1>
            <ul className="flex items-center gap-10 text-lg">
              <li>
                <a
                  href="/"
                  className="rainbow-text rainbow-hover rainbow-hover-light"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  href="/project"
                  className="rainbow-hover rainbow-hover-light"
                >
                  Project
                </a>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-8 py-2 border-none rounded-md ml-4"
                  href="#"
                >
                  CV
                </a>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="flex flex-col items-center py-10">
            <h2 className="text-4Xl md:text-5xl text-teal-600">
              Hello I,m Rama Kusuma
            </h2>

            <div className="max-w">
              <h3 className="ml-3 animate-typing overflow-hidden whitespace-nowrap border-r-4 border-r-white text-2xl md:text-3xl text-black dark:text-white mt-5">
                Fullstack Developer
              </h3>
            </div>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl text-justify">
              Detail-oriented recent graduate in Informatic Engineering with a
              passion for coding and software development. Proficient in
              fundamental programming languages such as JavaScript, TypeScript,
              and PHP, coupled with a solid understanding of database management
              and system analysis. Dedicated to continuous learning and
              professional growth in the field of programming.
            </p>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={rama} layout="fill" objectFit="cover" />
            </div>
            <div className="flex flex-row items-center mt-[50px] gap-10">
              <a
                href="https://github.com/ramakusuma10"
                className="relative p-0.5 inline-flex items-center justify-center font-bold overflow-hidden group rounded-md"
              >
                <span className="w-full h-full bg-gradient-to-br from-[#ff8a05] via-[#ff5478] to-[#ff00c6] group-hover:from-[#ff00c6] group-hover:via-[#ff5478] group-hover:to-[#ff8a05] absolute"></span>
                <span className="relative px-6 py-3 transition-all ease-out bg-gray-900 rounded-md group-hover:bg-opacity-0 duration-400">
                  <span className="relative text-white flex flex-row items-center gap-3">
                  <FaGithub className="w-[20px] h-[20px]"/> Github</span>
                </span>
              </a>
              <a
                href="CV/CV ATS & Portfolio - Rama Kusuma (Rev).pdf"
                className="relative p-0.5 inline-flex items-center justify-center font-bold overflow-hidden group rounded-md"
              >
                <span className="w-full h-full bg-gradient-to-br from-[#ff8a05] via-[#ff5478] to-[#ff00c6] group-hover:from-[#ff00c6] group-hover:via-[#ff5478] group-hover:to-[#ff8a05] absolute"></span>
                <span className="relative px-6 py-3 transition-all ease-out bg-gray-900 rounded-md group-hover:bg-opacity-0 duration-400">
                  <span className="relative text-white flex flex-row items-center gap-3">
                  <IoDocumentTextOutline className="w-[20px] h-[20px]"/> Lihat CV</span>
                </span>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
