import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { FaGithub } from "react-icons/fa";
import { IoLogoVercel } from "react-icons/io5";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import { Card, CardBody, Carousel } from "@material-tailwind/react";

export default function Project() {
  const [darkMode, setDarkMode] = useState(false);

  const handleDarkMode = () => {
    setDarkMode(!darkMode);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Rama Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-50 px-10 dark:bg-gray-900 md:px-20 lg:px-0">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white px-10 ">
            <h1 className="font-burtons text-xl">RAMADEVELOPED</h1>
            <ul className="flex items-center gap-10 text-lg">
              <li>
                <a href="/" className="rainbow-hover rainbow-hover-light">
                  Home
                </a>
              </li>
              <li>
                <a
                  href="/project"
                  className="rainbow-text rainbow-hover rainbow-hover-light"
                >
                  Project
                </a>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-8 py-2 border-none rounded-md ml-4"
                  href="#"
                >
                  CV
                </a>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={handleDarkMode}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="flex flex-col justify-center items-center px-2 py-10">
            <Card className="w-full max-w-[695px] p-6 shadow-md dark:bg-gray-800 bg-white">
              <CardBody>
                <h3
                  className={`text-2xl font-bold py-2 dark:text-white md:text-3xl animate-color-cycle text-center ${
                    darkMode ? "animate-dark-color-cycle" : ""
                  }`}
                >
                  LakoeApp
                </h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto md:text-xl text-justify mb-8">
                  Lakoe is a sales application built with React and NestJS,
                  designed to streamline and enhance the sales process with a
                  user-friendly interface and robust backend support. Lakoe
                  empowering businesses to efficiently manage products, orders,
                  and storefronts through its intuitive interface and robust
                  backend infrastructure.
                </p>
                <Carousel className="rounded-xl w-full">
                  <img
                    src="lakoe/lakoehome.jpeg"
                    className="h-[300px] w-full"
                  />
                  <img
                    src="lakoe/lakoelogin.jpeg"
                    className="h-[300px] w-full"
                  />
                  <img
                    src="lakoe/lakoeproduct.jpeg"
                    className="h-[300px] w-full"
                  />
                  <img
                    src="lakoe/lakoeseller.jpeg"
                    className="h-[300px] w-full"
                  />
                  <img
                    src="lakoe/lakoevariant.jpeg"
                    className="h-[300px] w-full"
                  />
                </Carousel>
                <h4 className="dark:text-white mt-8 text-2xl font-bold text-center">
                  Technologies
                </h4>
                <div className="flex flex-row justify-center mt-6 gap-6">
                  <a href="https://www.typescriptlang.org/">
                    <img
                      src="typescript.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://react.dev/">
                    <img src="reactjs.png" className="h-20 w-20 object-cover" />
                  </a>
                  <a href="https://tailwindcss.com/">
                    <img
                      src="tailwind.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://nestjs.com/">
                    <img src="nestjs.png" className="h-20 w-20 object-cover" />
                  </a>
                </div>
                <div className="flex flex-row justify-center mt-6 gap-6">
                  <a href="https://www.postgresql.org/">
                    <img
                      src="postgresql.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://www.prisma.io/">
                    <img
                      src={darkMode ? "prismalight.png" : "prisma.png"}
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                </div>
                <div className="border-b-2 mt-6"></div>
                <div className="flex flex-row w-full justify-center mt-10 gap-8">
                  <a
                    href="#_"
                    className="relative inline-flex items-center justify-center p-4 px-5 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out rounded-full shadow-xl group hover:ring-1 hover:ring-purple-500"
                  >
                    <span className="absolute inset-0 w-full h-full bg-gradient-to-br from-blue-600 via-purple-600 to-pink-700"></span>
                    <span className="absolute bottom-0 right-0 block w-64 h-64 mb-32 mr-4 transition duration-500 origin-bottom-left transform rotate-45 translate-x-24 bg-pink-500 rounded-full opacity-30 group-hover:rotate-90 ease"></span>
                    <span className="relative text-white flex flex-row items-center gap-2">
                      <FaGithub className="w-5 h-5" />
                      Link Github
                    </span>
                  </a>
                  <a
                    href="https://lakoe-frontend.vercel.app/"
                    target="_blank"
                    className="relative inline-flex items-center justify-center p-4 px-5 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out rounded-full shadow-xl group hover:ring-1 hover:ring-purple-500"
                  >
                    <span className="absolute inset-0 w-full h-full bg-gradient-to-br from-blue-600 via-purple-600 to-pink-700"></span>
                    <span className="absolute bottom-0 right-0 block w-64 h-64 mb-32 mr-4 transition duration-500 origin-bottom-left transform rotate-45 translate-x-24 bg-pink-500 rounded-full opacity-30 group-hover:rotate-90 ease"></span>
                    <span className="relative text-white flex flex-row items-center gap-2">
                      <IoLogoVercel className="w-5 h-5" />
                      Link Deploy
                    </span>
                  </a>
                </div>
              </CardBody>
            </Card>
            <Card className="w-full max-w-[695px] p-6 shadow-md dark:bg-gray-800 mt-10">
              <CardBody>
                <h3
                  className={`text-2xl font-bold py-2 dark:text-white md:text-3xl animate-color-cycle text-center ${
                    darkMode ? "animate-dark-color-cycle" : ""
                  }`}
                >
                  CircleApp
                </h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto md:text-xl text-justify mb-8">
                  Built with React and Express, our social media platform
                  provides a Twitter-like experience, enabling users to
                  seamlessly share updates, connect with others, upload images
                  and text, follow their favorite accounts, and engage through
                  likes, comments, and replies.
                </p>
                <Carousel className="rounded-xl w-full">
                  <img src="circle/Login.PNG" className="h-[300px] w-full" />
                  <img src="circle/Register.PNG" className="h-[300px] w-full" />
                  <img src="circle/Home.PNG" className="h-[300px] w-full" />
                  <img
                    src="circle/Following.PNG"
                    className="h-[300px] w-full"
                  />
                  <img src="circle/Search.PNG" className="h-[300px] w-full" />
                  <img src="circle/Profile.PNG" className="h-[300px] w-full" />
                </Carousel>
                <h4 className="dark:text-white mt-8 text-2xl font-bold text-center">
                  Technologies
                </h4>
                <div className="flex flex-row justify-center mt-6 gap-6">
                  <a href="https://www.typescriptlang.org/">
                    <img
                      src="typescript.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://react.dev/">
                    <img src="reactjs.png" className="h-20 w-20 object-cover" />
                  </a>
                  <a href="https://https://v2.chakra-ui.com/">
                    <img
                      src="chakraui.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://redux.js.org//">
                    <img src="redux.png" className="h-20 w-20 object-cover" />
                  </a>
                </div>
                <div className="flex flex-row justify-center mt-6 gap-6">
                  <a href="https://expressjs.com/">
                    <img
                      src={darkMode ? "expressjsputih.png" : "expressjs.png"}
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://www.postgresql.org/">
                    <img
                      src="postgresql.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://www.prisma.io/">
                    <img
                      src={darkMode ? "prismalight.png" : "prisma.png"}
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                </div>
                <div className="border-b-2 mt-6"></div>
                <div className="flex flex-row w-full justify-center mt-10 gap-8">
                  <a
                    href="https://github.com/ramakusuma10/CircleApp"
                    class="relative inline-flex items-center justify-center p-4 px-5 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out rounded-full shadow-xl group hover:ring-1 hover:ring-purple-500"
                  >
                    <span className="absolute inset-0 w-full h-full bg-gradient-to-br from-blue-600 via-purple-600 to-pink-700"></span>
                    <span className="absolute bottom-0 right-0 block w-64 h-64 mb-32 mr-4 transition duration-500 origin-bottom-left transform rotate-45 translate-x-24 bg-pink-500 rounded-full opacity-30 group-hover:rotate-90 ease"></span>
                    <span className="relative text-white flex flex-row items-center gap-2">
                      <FaGithub className="w-5 h-5" />
                      Link Github FE
                    </span>
                  </a>
                  <a
                    href="https://github.com/ramakusuma10/CircleAppBE"
                    class="relative inline-flex items-center justify-center p-4 px-5 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out rounded-full shadow-xl group hover:ring-1 hover:ring-purple-500"
                  >
                    <span className="absolute inset-0 w-full h-full bg-gradient-to-br from-blue-600 via-purple-600 to-pink-700"></span>
                    <span className="absolute bottom-0 right-0 block w-64 h-64 mb-32 mr-4 transition duration-500 origin-bottom-left transform rotate-45 translate-x-24 bg-pink-500 rounded-full opacity-30 group-hover:rotate-90 ease"></span>
                    <span className="relative text-white flex flex-row items-center gap-2">
                      <FaGithub className="w-5 h-5" />
                      Link Github BE
                    </span>
                  </a>
                  <a
                    href="https://lakoe-frontend.vercel.app/"
                    target="_blank"
                    className="relative inline-flex items-center justify-center p-4 px-5 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out rounded-full shadow-xl group hover:ring-1 hover:ring-purple-500"
                  >
                    <span className="absolute inset-0 w-full h-full bg-gradient-to-br from-blue-600 via-purple-600 to-pink-700"></span>
                    <span className="absolute bottom-0 right-0 block w-64 h-64 mb-32 mr-4 transition duration-500 origin-bottom-left transform rotate-45 translate-x-24 bg-pink-500 rounded-full opacity-30 group-hover:rotate-90 ease"></span>
                    <span className="relative text-white flex flex-row items-center gap-2">
                      <IoLogoVercel className="w-5 h-5" />
                      Link Deploy
                    </span>
                  </a>
                </div>
              </CardBody>
            </Card>
            <Card className="w-full max-w-[695px] p-6 shadow-md dark:bg-gray-800 mt-10">
              <CardBody>
                <h3
                  className={`text-2xl font-bold py-2 dark:text-white md:text-3xl animate-color-cycle text-center ${
                    darkMode ? "animate-dark-color-cycle" : ""
                  }`}
                >
                  TrueOrFalse
                </h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-2xl mx-auto md:text-xl text-justify mb-8">
                  A true or false game in which the winner is determined by the
                  last person remaining in the game. The Winner will get a prize
                  in the form of coins, This game includes a feature that allow
                  users to log in via Google and the option to purchase
                  diamonds. These diamons can be used to obtain premium avatars.
                </p>
                <div className="flex flex-col items-center">
                  <Carousel className="rounded-xl w-[300px]">
                  <img
                      src="trivia/Register.jpeg"
                      className="h-[600px] w-[300px]"
                    />
                    <img
                      src="trivia/Home.jpg"
                      className="h-[600px] w-[300px]"
                    />
                    <img
                      src="trivia/Game.jpeg"
                      className="h-[600px] w-{200px]"
                    />
                  </Carousel>
                </div>
                <h4 className="dark:text-white mt-8 text-2xl font-bold text-center">
                  Technologies
                </h4>
                <div className="flex flex-row justify-center mt-6 gap-6">
                  <a href="https://www.typescriptlang.org/">
                    <img
                      src="typescript.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://react.dev/">
                    <img src="reactjs.png" className="h-20 w-20 object-cover" />
                  </a>
                  <a href="https://reactnativeelements.com/">
                    <img
                      src="rne.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://nestjs.com/">
                    <img src="nestjs.png" className="h-20 w-20 object-cover" />
                  </a>
                </div>
                <div className="flex flex-row justify-center mt-6 gap-6">
                  <a href="https://www.postgresql.org/">
                    <img
                      src="postgresql.png"
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://www.prisma.io/">
                    <img
                      src={darkMode ? "prismalight.png" : "prisma.png"}
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                  <a href="https://www.socket.io/">
                    <img
                      src={darkMode ? "socketio_logo_icon_white.png" : "socketio_logo_icon.png"}
                      className="h-20 w-20 object-cover"
                    />
                  </a>
                </div>
                <div className="border-b-2 mt-6"></div>
                <div className="flex flex-row w-full justify-center mt-10 gap-8">
                  <a
                    href="https://github.com/ramakusuma10/CircleApp"
                    className="relative inline-flex items-center justify-center p-4 px-5 py-3 overflow-hidden font-medium text-indigo-600 transition duration-300 ease-out rounded-full shadow-xl group hover:ring-1 hover:ring-purple-500"
                  >
                    <span className="absolute inset-0 w-full h-full bg-gradient-to-br from-blue-600 via-purple-600 to-pink-700"></span>
                    <span className="absolute bottom-0 right-0 block w-64 h-64 mb-32 mr-4 transition duration-500 origin-bottom-left transform rotate-45 translate-x-24 bg-pink-500 rounded-full opacity-30 group-hover:rotate-90 ease"></span>
                    <span className="relative text-white flex flex-row items-center gap-2">
                      <FaGithub className="w-5 h-5" />
                      Link Github
                    </span>
                  </a>
                </div>
              </CardBody>
            </Card>
          </div>
        </section>
      </main>
    </div>
  );
}
